apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: vuln-critical-sarif-cve
spec:
  images:
    - glob: "gcr.io/chainguard-demo/*"
  authorities:
  - keyless:
      url: https://fulcio.sigstore.dev
      identities:
      - issuer: https://token.actions.githubusercontent.com
        subject: https://github.com/chainguard-dev/source-integrity-demo/.github/workflows/release.yaml@refs/heads/main
    attestations:
    - predicateType: vuln
      name: vulnkeyless
      policy:
        type: cue
        data: |
          import (
          "encoding/json"
          "strings"
          "strconv"
        )
        #Predicate: {
          Data: string
          Timestamp: string
          ...
        }
        predicate: {
            scanner: {
              result: {
                runs: [...{
                  tool: {
                    driver: {
                      rules: [...{
                        id: id
                          properties: {
                            "security-severity": string
                            severityFloat: strconv.ParseFloat(properties."security-severity", 16)
                            if severityFloat > 9.0 {
                              expectedError: "no error",
                              err: strings.Join(["Error: contains high severity vulnerability", id, properties."security-severity"], " ")
                              expectedError: err
                           }
                         }
                      }]
                    }
                  }
                }]
              }
            }
          }

